testing ip route

diff --git a/.github/workflows/integration_fakeserver_tests.yml b/.github/workflows/integration_fakeserver_tests.yml
--- a/.github/workflows/integration_fakeserver_tests.yml
+++ b/.github/workflows/integration_fakeserver_tests.yml
@@ -40,28 +40,22 @@ jobs:
         with:
           version: "v1.24.0"
       
-      - name: Set up KIND Cluster with Host Networking
+      - name: Install Minikube
         run: |
-          cat <<EOF > kind-config.yaml
-          kind: Cluster
-          apiVersion: kind.x-k8s.io/v1alpha4
-          name: github-actions
-          nodes:
-            - role: control-plane
-              extraPortMappings:
-                - containerPort: 50053
-                  hostPort: 50053
-                  protocol: TCP
-                - containerPort: 50051
-                  hostPort: 50051
-                  protocol: TCP
+          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
+          sudo install minikube-linux-amd64 /usr/local/bin/minikube
 
-          EOF
-          kind create cluster --name github-actions --config kind-config.yaml
-
-      - name: Set kubectl context for KIND
+      - name: Start Minikube
         run: |
-          kubectl cluster-info --context kind-github-actions
+          minikube start --driver=docker
+  
+      - name: Wait for Minikube to be ready
+        run: |
+          minikube kubectl -- get nodes
+
+      - name: Run ip route
+        run: |
+          ip route
 
       - name: Set up Helm
         uses: azure/setup-helm@v4.2.0
@@ -109,23 +103,23 @@ jobs:
           go test -v ./fakeserver/...
           
 
-      - name: Exec into Pod and Test Connections
-        run: |
-          POD_NAME=$(kubectl get pods -n illumio-cloud -o jsonpath='{.items[0].metadata.name}')
-          echo "Pod name: $POD_NAME"
+      # - name: Exec into Pod and Test Connections
+      #   run: |
+      #     POD_NAME=$(kubectl get pods -n illumio-cloud -o jsonpath='{.items[0].metadata.name}')
+      #     echo "Pod name: $POD_NAME"
 
-          # Define the external server IPs and ports for both HTTP and gRPC servers
-          EXTERNAL_IP="host.docker.internal"
-          HTTP_PORT=50053
-          GRPC_PORT=50051
+      #     # Define the external server IPs and ports for both HTTP and gRPC servers
+      #     EXTERNAL_IP="host.docker.internal"
+      #     HTTP_PORT=50053
+      #     GRPC_PORT=50051
 
-          # Test connection to the HTTP fake server
-          echo "Testing HTTP connection to $EXTERNAL_IP:$HTTP_PORT from pod..."
-          kubectl exec -it $POD_NAME -n illumio-cloud -- curl -v http://$EXTERNAL_IP:$HTTP_PORT || echo "Failed to connect to HTTP server at $EXTERNAL_IP:$HTTP_PORT"
+      #     # Test connection to the HTTP fake server
+      #     echo "Testing HTTP connection to $EXTERNAL_IP:$HTTP_PORT from pod..."
+      #     kubectl exec -it $POD_NAME -n illumio-cloud -- curl -v http://$EXTERNAL_IP:$HTTP_PORT || echo "Failed to connect to HTTP server at $EXTERNAL_IP:$HTTP_PORT"
 
-          # Test connection to the gRPC server
-          echo "Testing gRPC connection to $EXTERNAL_IP:$GRPC_PORT from pod..."
-          kubectl exec -it $POD_NAME -n illumio-cloud -- grpcurl -plaintext $EXTERNAL_IP:$GRPC_PORT list || echo "Failed to connect to gRPC server at $EXTERNAL_IP:$GRPC_PORT"
+      #     # Test connection to the gRPC server
+      #     echo "Testing gRPC connection to $EXTERNAL_IP:$GRPC_PORT from pod..."
+      #     kubectl exec -it $POD_NAME -n illumio-cloud -- grpcurl -plaintext $EXTERNAL_IP:$GRPC_PORT list || echo "Failed to connect to gRPC server at $EXTERNAL_IP:$GRPC_PORT"
 
       - name: Fetch Kubernetes Pod logs
         run: |
