made chages in the schema

diff --git a/.github/workflows/update-schema.yml b/.github/workflows/update-schema.yml
--- a/.github/workflows/update-schema.yml
+++ b/.github/workflows/update-schema.yml
@@ -33,6 +33,12 @@ jobs:
         run: |
           git diff --exit-code cloud-operator/values.schema.json || echo "changes=true" >> $GITHUB_OUTPUT
 
+      - name: Fail if changes in PR
+        if: steps.git-check.outputs.changes == 'true' && github.event_name == 'pull_request'
+        run: |
+          echo "::error::Schema file needs to be updated. Please run 'helm schema-gen cloud-operator -o cloud-operator/values.schema.json' locally and commit the changes."
+          exit 1
+
       - name: Commit changes
         if: steps.git-check.outputs.changes == 'true' && github.event_name != 'pull_request'
         run: |
